-- ============================================================
-- PROJECT 1: UNIVERSITY ACADEMIC MANAGEMENT SYSTEM
-- File: 06_enrollment.sql
-- ============================================================

-- 1. CREATE TABLE: ENROLLMENT

CREATE TABLE Enrollment (
    enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL,
    course_id NUMBER NOT NULL,
    semester VARCHAR2(20),
    enrollment_date DATE,

    CONSTRAINT uq_enrollment
        UNIQUE (student_id, course_id, semester),

    CONSTRAINT fk_enrollment_student
        FOREIGN KEY (student_id)
        REFERENCES Student(student_id),

    CONSTRAINT fk_enrollment_course
        FOREIGN KEY (course_id)
        REFERENCES Course(course_id)
);

-- 2. SAMPLE DATA

INSERT INTO Enrollment
    (student_id, course_id, semester, enrollment_date)
VALUES
    (1001, 301, '2024-Odd', DATE '2024-07-01');

INSERT INTO Enrollment
    (student_id, course_id, semester, enrollment_date)
VALUES
    (1002, 302, '2024-Odd', DATE '2024-07-01');

INSERT INTO Enrollment
    (student_id, course_id, semester, enrollment_date)
VALUES
    (1003, 301, '2024-Odd', DATE '2024-07-01');

COMMIT;

-- 3. VERIFY ENROLLMENT TABLE

SELECT * FROM Enrollment;
