-- ============================================================
-- PROJECT 1: UNIVERSITY ACADEMIC MANAGEMENT SYSTEM
-- File: ddl.sql
-- ============================================================


-- ============================================================
-- 1. DEPARTMENT TABLE
-- ============================================================

CREATE TABLE Department (
    dept_id NUMBER PRIMARY KEY,
    dept_name VARCHAR2(100) NOT NULL UNIQUE,
    hod_id NUMBER,
    established_year NUMBER(4),

    CONSTRAINT chk_department_year
        CHECK (established_year BETWEEN 1800 AND 2100)
);


-- ============================================================
-- 2. STUDENT TABLE
-- ============================================================

CREATE TABLE Student (
    student_id NUMBER PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    dob DATE,
    email VARCHAR2(100) NOT NULL UNIQUE,
    address VARCHAR2(200),
    dept_id NUMBER NOT NULL,

    CONSTRAINT fk_student_department
        FOREIGN KEY (dept_id)
        REFERENCES Department(dept_id)
);


-- ============================================================
-- 3. STUDENT_PHONE TABLE
-- ============================================================

CREATE TABLE Student_Phone (
    student_id NUMBER NOT NULL,
    phone_number VARCHAR2(15) NOT NULL,

    CONSTRAINT pk_student_phone
        PRIMARY KEY (student_id, phone_number),

    CONSTRAINT fk_phone_student
        FOREIGN KEY (student_id)
        REFERENCES Student(student_id)
        ON DELETE CASCADE,

    CONSTRAINT chk_phone_format
        CHECK (LENGTH(phone_number) >= 10)
);


-- ============================================================
-- 4. FACULTY TABLE
-- ============================================================

CREATE TABLE Faculty (
    faculty_id NUMBER PRIMARY KEY,
    faculty_name VARCHAR2(100) NOT NULL,
    qualification VARCHAR2(100),
    phone VARCHAR2(15) UNIQUE,
    email VARCHAR2(100) UNIQUE,
    department_id NUMBER NOT NULL,

    CONSTRAINT fk_faculty_department
        FOREIGN KEY (department_id)
        REFERENCES Department(dept_id)
);


-- ============================================================
-- 5. DEPARTMENT HOD FOREIGN KEY
-- ============================================================

ALTER TABLE Department
ADD CONSTRAINT fk_department_hod
FOREIGN KEY (hod_id)
REFERENCES Faculty(faculty_id);


-- ============================================================
-- 6. COURSE TABLE
-- ============================================================

CREATE TABLE Course (
    course_id NUMBER PRIMARY KEY,
    course_name VARCHAR2(100) NOT NULL,
    credits NUMBER NOT NULL,
    semester NUMBER NOT NULL,
    faculty_id NUMBER NOT NULL,
    department_id NUMBER NOT NULL,

    CONSTRAINT ck_course_credits
        CHECK (credits BETWEEN 1 AND 5),

    CONSTRAINT ck_course_semester
        CHECK (semester BETWEEN 1 AND 8),

    CONSTRAINT fk_course_faculty_01
        FOREIGN KEY (faculty_id)
        REFERENCES Faculty(faculty_id),

    CONSTRAINT fk_course_department_01
        FOREIGN KEY (department_id)
        REFERENCES Department(dept_id)
);


-- ============================================================
-- 7. ENROLLMENT TABLE
-- ============================================================

CREATE TABLE Enrollment (
    enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL,
    course_id NUMBER NOT NULL,
    semester VARCHAR2(20),
    enrollment_date DATE,

    CONSTRAINT uq_enrollment
        UNIQUE (student_id, course_id, semester),

    CONSTRAINT fk_enrollment_student
        FOREIGN KEY (student_id)
        REFERENCES Student(student_id),

    CONSTRAINT fk_enrollment_course
        FOREIGN KEY (course_id)
        REFERENCES Course(course_id)
);


-- ============================================================
-- 8. RESULTS TABLE
-- ============================================================

CREATE TABLE Results (
    result_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id NUMBER UNIQUE NOT NULL,
    marks_obtained NUMBER(5,2) NOT NULL,
    total_marks NUMBER(5,2) DEFAULT 100 NOT NULL,
    grade CHAR(2),
    exam_date DATE,

    CONSTRAINT ck_results_marks_nonnegative
        CHECK (marks_obtained >= 0),

    CONSTRAINT ck_results_total_positive
        CHECK (total_marks > 0),

    CONSTRAINT ck_results_marks_within_total
        CHECK (marks_obtained <= total_marks),

    CONSTRAINT fk_results_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES Enrollment(enrollment_id)
);


-- ============================================================
-- END OF ddl.sql
-- ============================================================